#!/bin/bash -e

. $(dirname $0)/build-properties
. $(dirname $0)/pkgversion

PROGRAM="binutils-${BINUTILS_VER}"
TARBALL="$PROGRAM.tar.*"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	mkdir -v build
	cd       build
	
	CC=$LFS_TGT-gcc                \
	AR=$LFS_TGT-ar                 \
	RANLIB=$LFS_TGT-ranlib         \
	../configure                   \
		--prefix=/tools            \
		--disable-nls              \
		--disable-werror           \
        --enable-multilib    \
		--with-lib-path=/tools/lib32:/tools/lib \
		--with-sysroot
	make tooldir=/tools
    make tooldir=/tools install
    make -C ld clean
    make -C ld LIB_PATH=/usr/lib32:/usr/lib
    cp ld/ld-new /tools/bin
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
