#!/bin/bash -e

. $(dirname $0)/build-properties
. $(dirname $0)/pkgversion

PROGRAM="binutils-${BINUTILS_VER}"
TARBALL="$PROGRAM.tar.*"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {

	mkdir -v build
	cd       build
	
	../configure --prefix=/tools            \
				 --with-sysroot=$LFS        \
				 --with-lib-path=/tools/lib \
				 --target=$LFS_TGT          \
				 --disable-nls              \
				 --disable-werror			\
				 --enable-multilib     		\
                 --with-lib-path=/tools/lib32:/tools/lib
	make
	make install
	mkdir /tools/lib
    ln -s lib /tools/lib64
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
