#!/bin/bash -e

. $(dirname $0)/build-properties
. $(dirname $0)/pkgversion

PROGRAM="glibc-${GLIBC_VER}"
TARBALL="$PROGRAM.tar.*"

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	DIRECTORY=`tar -tf $TARBALL | cut -d/ -f1 | uniq`
	rm -rf $DIRECTORY || true
	tar xf $TARBALL
	cd $DIRECTORY
fi

{ time \
   {
	   
	patch -Np1 -i ${SOURCE_DIR}/glibc-pure64.patch

	mkdir -v build
	cd       build
	
	echo slibdir=/tools/lib > configparms
	
	../configure                             \
		  --prefix=/tools                    \
          --libdir=/tools/lib                \
          --libexecdir=/tools/lib            \
		  --host=$LFS_TGT                    \
		  --build=$(../scripts/config.guess) \
		  --enable-kernel=2.6.32             \
          --enable-obsolete-nsl              \
          --enable-obsolete-rpc              \
		  --with-headers=/tools/include      \
		  libc_cv_forced_unwind=yes          \
		  libc_cv_c_cleanup=yes				 \
          libc_cv_ssp=no
	make
	make install
	rm -rf /tools/lib/libnsl.{a,so}
	
	cd ..
	
	mkdir build32
	cd    build32
	
	echo slibdir=/tools/lib32 > configparms
    CC="$LFS_TGT-gcc -m32"                   \
    ../configure                             \
          --prefix=/tools                    \
          --libdir=/tools/lib32              \
          --libexecdir=/tools/lib32          \
          --host=i686-lfs-linux-gnu          \
          --build=$(../scripts/config.guess) \
          --enable-kernel=2.6.32             \
          --enable-obsolete-nsl              \
          --enable-obsolete-rpc              \
          --with-headers=/tools/include      \
          libc_cv_forced_unwind=yes          \
          libc_cv_c_cleanup=yes              \
          libc_cv_ssp=no
    make
    make install install_root=${PWD}/dest
    mv dest/tools/lib32 /tools
    mv dest/tools/include/gnu/lib-names-32.h /tools/include/gnu
    mv dest/tools/include/gnu/stubs-32.h /tools/include/gnu

    rm -rf /tools/lib32/libnsl.{a,so}

    mkdir -p /tools/lib/locale
    localedef -i en_US -f UTF-8 en_US.UTF-8
          
   }
} 2>&1 | tee ${LOG_DIR}/$0.log

[ $PIPESTATUS = 0 ] || exit $PIPESTATUS

cd $SOURCE_DIR
if [ "$TARBALL" != "" ]; then
	rm -rf $DIRECTORY
fi
