#!/bin/bash

strip --strip-debug /tools/lib/*
strip --strip-debug /tools/lib32/*
/usr/bin/strip --strip-unneeded /tools/{,s}bin/*
rm -rf /tools/{,share}/{info,man,doc}
find /tools/{lib,lib32,libexec} -name \*.la -delete
