#!/bin/bash

. $(dirname $0)/build-properties
. $(dirname $0)/pkgversion

src=(
http://ftp.gnu.org/gnu/binutils/binutils-${BINUTILS_VER}.tar.xz
http://ftp.gnu.org/gnu/gcc/gcc-${GCC_VER}/gcc-${GCC_VER}.tar.xz
http://www.mpfr.org/mpfr-${MPFR_VER}/mpfr-${MPFR_VER}.tar.xz
http://ftp.gnu.org/gnu/gmp/gmp-${GMP_VER}.tar.xz
https://ftp.gnu.org/gnu/mpc/mpc-${MPC_VER}.tar.gz
https://www.kernel.org/pub/linux/kernel/v4.x/linux-${LINUX_VER}.tar.xz
http://ftp.gnu.org/gnu/glibc/glibc-${GLIBC_VER}.tar.xz
https://downloads.sourceforge.net/tcl/tcl${TCLCORE_VER}-src.tar.gz
https://sourceforge.net/projects/expect/files/Expect/${EXPECT_VER}/expect${EXPECT_VER}.tar.gz
http://ftp.gnu.org/gnu/dejagnu/dejagnu-${DEJAGNU_VER}.tar.gz
http://ftp.gnu.org/gnu//ncurses/ncurses-${NCURSES_VER}.tar.gz
http://ftp.gnu.org/gnu/bash/bash-${BASH_VER}.tar.gz
http://ftp.gnu.org/gnu/bison/bison-${BISON_VER}.tar.xz
http://www.bzip.org/${BZIP_VER}/bzip2-${BZIP_VER}.tar.gz
http://ftp.gnu.org/gnu/coreutils/coreutils-${COREUTILS_VER}.tar.xz
http://ftp.gnu.org/gnu/diffutils/diffutils-${DIFFUTILS_VER}.tar.xz
ftp://ftp.astron.com/pub/file/file-${FILE_VER}.tar.gz
http://ftp.gnu.org/gnu/findutils/findutils-${FINDUTILS_VER}.tar.gz
http://ftp.gnu.org/gnu/gawk/gawk-${GAWK_VER}.tar.xz
http://ftp.gnu.org/gnu/gettext/gettext-${GETTEXT_VER}.tar.xz
http://ftp.gnu.org/gnu/grep/grep-${GREP_VER}.tar.xz
http://ftp.gnu.org/gnu/gzip/gzip-${GZIP_VER}.tar.xz
http://ftp.gnu.org/gnu/m4/m4-${M4_VER}.tar.xz
http://ftp.gnu.org/gnu/make/make-${MAKE_VER}.tar.bz2
http://ftp.gnu.org/gnu/patch/patch-${PATCH_VER}.tar.xz
http://www.cpan.org/src/5.0/perl-${PERL_VER}.tar.xz
http://ftp.gnu.org/gnu/sed/sed-${SED_VER}.tar.xz
http://ftp.gnu.org/gnu/tar/tar-${TAR_VER}.tar.xz
http://ftp.gnu.org/gnu/texinfo/texinfo-${TEXINFO_VER}.tar.xz
https://www.kernel.org/pub/linux/utils/util-linux/v${UTILLINUX_VER::4}/util-linux-${UTILLINUX_VER}.tar.xz
http://tukaani.org/xz/xz-${XZ_VER}.tar.xz
https://openssl.org/source/openssl-${OPENSSL_VER}.tar.gz
http://anduin.linuxfromscratch.org/BLFS/other/certdata.txt
https://ftp.gnu.org/gnu/wget/wget-${WGET_VER}.tar.gz
http://zlib.net/zlib-${ZLIB_VER}.tar.xz
https://www.nano-editor.org/dist/v${NANO_VER::3}/nano-${NANO_VER}.tar.xz
)

fetchsource() {
	
	tarballname=$(echo $1 | rev | cut -d / -f 1 | rev)
	WGETCMD="wget --passive-ftp --tries=3 --waitretry=3 --output-document=$2/$tarballname.partial"
	WGETRESUME="-c"
	
	if [ -f $2/$tarballname ]; then
		echo "Source file $tarballname found."
		return 0
	else
		if [ -f $2/$tarballname.partial ]; then
			echo "Resuming $i."
			$WGETCMD $WGETRESUME $1
		else
			echo "Downloading $i."
			$WGETCMD $1
		fi
	fi
	
	if [ $? = 0 ]; then
		mv $2/$tarballname.partial $2/$tarballname
	fi
	
}

[ -d $SOURCE_DIR ] || mkdir -p $SOURCE_DIR

for i in ${src[@]}; do
	fetchsource $i $SOURCE_DIR
done

echo
echo "Checking broken sources, plese wait..."
for s in ${src[@]}; do
	tarballname=$(echo $s | rev | cut -d / -f 1 | rev)
	case $tarballname in
		*.tar.*)
			tar -tf $SOURCE_DIR/$tarballname &>/dev/null
			[ $? = 0 ] || echo "$tarballname is broken!"
		;;
	esac
done

exit 0
